name: Run Postman API Tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1-5'  # every weekday at 6 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Run Collection & Generate HTML Report
        run: |
          newman run collections/DogCeoAPI.postman_collection.json \
          -e environments/DogCeo_Env.postman_environment.json \
          -r cli,html \
          --reporter-html-export newman/DogCeo_Report.html

